### ISSUE TITLE
Doesn't work in older versions of OS X (Before El Capitan)

### ISSUE THREAD

**Issue by impsart** [einancunlu/Disconnect-for-Sketch#1] opened 2015-12-23 09:18 UTC
Doesn't seem to work for me. It says "Could not launch plugin".

Installed via Toolbox.
Restarted Sketch.
Sketch 3.4.4

**Comment by einancunlu** [comment] 2015-12-23 09:28
Sorry to hear that, what is your OSX version?

**Comment by impsart** [comment] 2015-12-23 10:08
I'm on OSX 10.10.5.
Also tried manual installation, but still outputs the same.

If it is just me, it might be a conflict with some of the plugins I have installed.
I'll try to disable the rest later and see if it is.

**Comment by einancunlu** [comment] 2015-12-23 10:18
I think it is caused by using older version of OSX. I used 10.11 as deployment target when developing the plugin window. But I compiled it with changing the deployment target to 10.10 for you, it gave some warnings but didn't stop me doing. So I'm not sure if it works but worth trying:

[Uploading Disconnect.sketchplugin.zip…]()

**Comment by einancunlu** [comment] 2015-12-23 10:20
Oh sorry, pressed wrong button. : ) File is uploading still, somehow it's slow.

**Comment by einancunlu** [comment] 2015-12-23 10:25
It doesn't seem uploading, use this link to download: https://www.dropbox.com/sh/4fpotxyxene9df5/AAANmQgpjuuOpN5elOenq2lQa?dl=0

**Comment by impsart** [comment] 2015-12-23 10:40
I still can't get it to work. Might have to dig in a bit later.
Thanks anyways!

**Comment by smaretto** [comment] 2016-01-12 14:59
Same issue, still writes me Could not launch plugin. Still on Yosemite, last version of Sketch... Hope it will be fixed cause your plugin fixes a big issue with sketch: repetitive actions.

**Comment by einancunlu** [comment] 2016-01-15 09:43
Updated the plugin and added compatibility for older OS X versions. Now it should be fixed, please try and let me know if won't work still. : )

**Closed as completed by einancunlu** 2016-01-15 09:43 UTC
